// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtDj0m7fZdxmy4dvjRzVKNKOoBoNRru1Y',
    appId: '1:431233888741:web:dbe4e9948d8a8185e33f0c',
    messagingSenderId: '431233888741',
    projectId: 'toto-food---delivery',
    authDomain: 'toto-food---delivery.firebaseapp.com',
    storageBucket: 'toto-food---delivery.firebasestorage.app',
    measurementId: 'G-NZXRLPWDSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC6ffGgWSWFhXgYWlxM5uO0wcjrAVlKEo',
    appId: '1:431233888741:android:7851f3c8033b0a59e33f0c',
    messagingSenderId: '431233888741',
    projectId: 'toto-food---delivery',
    storageBucket: 'toto-food---delivery.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwFTXhwZohGIdZ9TuY69I7jcdzTkibBHM',
    appId: '1:431233888741:ios:b7bdd98b00b0ee7be33f0c',
    messagingSenderId: '431233888741',
    projectId: 'toto-food---delivery',
    storageBucket: 'toto-food---delivery.firebasestorage.app',
    iosClientId: '431233888741-e2tq05bkl6vidvjbr9tskd2948tffipp.apps.googleusercontent.com',
    iosBundleId: 'com.toto.food.user',
  );
}
