default_platform(:ios)

platform :ios do
  lane :upload_build_to_app_store do

    # ১. এপিআই কী জেনারেট করা
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false
    )

    # ২. সরাসরি আইপিএ ফাইলটি অ্যাপল স্টোরে আপলোড করার নির্দেশ
    deliver(
      api_key: api_key,
      ipa: "./build/ios/ipa/Runner.ipa",
      skip_binary_upload: false,
      force: true,
      app_version: "1.0.0",
      automatic_release: true,
      skip_metadata: true,
      skip_screenshots: true,
      run_precheck_before_submit: false
    )
  end
end
