default_platform(:ios)

platform :ios do
  lane :upload_build_to_app_store do

    # ১. এপিআই কী জেনারেট করা
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false
    )

    # ২. সরাসরি এক্সকোড কম্পাইলার লেভেলে এপিআই কী ম্যাপ করা (xcargs ট্রিক)
    build_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      clean: true,
      output_directory: "./build/ios/ipa",
      export_options: {
        api_key: api_key
      },
      # এখানে আমরা এক্সকোড কম্পাইলারকে সরাসরি এপিআই টোকেন দিয়ে অথেন্টিকেট করছি
      xcargs: "-allowProvisioningUpdates -authenticationKeyID #{ENV['APP_STORE_CONNECT_KEY_ID']} -authenticationKeyIssuerID #{ENV['APP_STORE_CONNECT_ISSUER_ID']}"
    )

    # ৩. অ্যাপল স্টোরে বিল্ড আপলোড
    deliver(
      api_key: api_key,
      ipa: "./build/ios/ipa/Runner.ipa",
      skip_binary_upload: false,
      force: true,
      app_version: "1.0.0",
      automatic_release: true,
      skip_metadata: true,
      skip_screenshots: true,
      run_precheck_before_submit: false
    )
  end
end
