name: Deploy Build to App Store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Clean and Pre-Build via Flutter
        run: |
          flutter pub get
          flutter build ios --config-only

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      # Gemfile ছাড়াই সরাসরি ফাস্টলেন ইনস্টল করার ব্যবস্থা
      - name: Install Fastlane Directly
        run: |
          gem install fastlane --no-document

      - name: Build and Deploy to App Store
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        # এখানে bundle exec কেটে সরাসরি fastlane রান করানো হচ্ছে
        run: fastlane ios upload_build_to_app_store
