name: Deploy Build to App Store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # ১. আইওএস ফোল্ডারের পুরনো ক্যাশ ও লক ফাইল ডিলিট করে সম্পূর্ণ ফ্রেশ পড ইনস্টল করার স্ক্রিপ্ট
      - name: Clean and Install iOS Dependencies
        run: |
          flutter pub get
          cd ios
          rm -rf Pods Podfile.lock /Users/runner/Library/Developer/Xcode/DerivedData
          pod repo update
          pod install --repo-update

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Bundler & Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Build and Deploy to App Store
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        run: bundle exec fastlane ios upload_build_to_app_store
